name: 'infradata_brasil'
version: '1.0.0'
config-version: 2

profile: 'infradata_brasil'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  infradata_brasil:
    staging:
      +materialized: view
    marts:
      +materialized: table
      exposure:
        +materialized: view
